services:
  - type: web
    name: demanda
    runtime: docker
    plan: free
    dockerfilePath: ./docker/php/Dockerfile
    dockerContext: .
    autoDeploy: true
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/firebase_credenciais.json
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
