services:
  - type: web
    name: demanda
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile.render
    dockerContext: .
    autoDeploy: true
    envVars:
      - key: DB_HOST
        value: localhost
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: costureira_db
      - key: DB_USERNAME
        value: costureira_user
      - key: DB_PASSWORD
        value: costureira_pass
      - key: DOCKER_ENV
        value: true
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/firebase_credenciais.json
